name: tests


on:
  push:
    paths-ignore:
      - README.md
      - setup.py
      - .gitignore
      - Sample Web Response.txt
      - .github/workflows/python-publish.yml
  pull_request:
  workflow_dispatch:


jobs:
  test:

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: pip install -U pip setuptools wheel

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install test deps
        run: pip install pytest

      - name: Run tests
        run: python -m pytest
      