name: tests


on:
  push:
    paths-ignore:
      - README.md
      - setup.py
      - .gitignore
      - Sample Web Response.txt
      - .github/workflows/python-publish.yml
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'


jobs:
  test:

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: pip install -U pip wheel

      - name: Install deps
        run: pip install .

      - name: Install test deps
        run: pip install pytest

      - name: Run tests
        run: pytest
      
